[package]
name    = "uniblocks-codegen"
version = "0.0.0"
authors = ["Casey Rodarmor <casey@rodarmor.com>"]
publish = false

[dependencies]
failure     = "0.1.1"
lazy_static = "1.0.0"
proc-macro2 = "0.3.8"
quote       = "0.5.2"
regex       = "1.0.0"
syn         = "0.13.10"
