#[derive(Clone, Copy, Eq, PartialEq, Ord, PartialOrd)]
pub enum Block {
    BasicLatin,
    Latin1Supplement,
    LatinExtendedA,
    LatinExtendedB,
    IPAExtensions,
    SpacingModifierLetters,
    CombiningDiacriticalMarks,
    GreekandCoptic,
    Cyrillic,
    CyrillicSupplement,
    Armenian,
    Hebrew,
    Arabic,
    Syriac,
    ArabicSupplement,
    Thaana,
    NKo,
    Samaritan,
    Mandaic,
    SyriacSupplement,
    ArabicExtendedA,
    Devanagari,
    Bengali,
    Gurmukhi,
    Gujarati,
    Oriya,
    Tamil,
    Telugu,
    Kannada,
    Malayalam,
    Sinhala,
    Thai,
    Lao,
    Tibetan,
    Myanmar,
    Georgian,
    HangulJamo,
    Ethiopic,
    EthiopicSupplement,
    Cherokee,
    UnifiedCanadianAboriginalSyllabics,
    Ogham,
    Runic,
    Tagalog,
    Hanunoo,
    Buhid,
    Tagbanwa,
    Khmer,
    Mongolian,
    UnifiedCanadianAboriginalSyllabicsExtended,
    Limbu,
    TaiLe,
    NewTaiLue,
    KhmerSymbols,
    Buginese,
    TaiTham,
    CombiningDiacriticalMarksExtended,
    Balinese,
    Sundanese,
    Batak,
    Lepcha,
    OlChiki,
    CyrillicExtendedC,
    SundaneseSupplement,
    VedicExtensions,
    PhoneticExtensions,
    PhoneticExtensionsSupplement,
    CombiningDiacriticalMarksSupplement,
    LatinExtendedAdditional,
    GreekExtended,
    GeneralPunctuation,
    SuperscriptsandSubscripts,
    CurrencySymbols,
    CombiningDiacriticalMarksforSymbols,
    LetterlikeSymbols,
    NumberForms,
    Arrows,
    MathematicalOperators,
    MiscellaneousTechnical,
    ControlPictures,
    OpticalCharacterRecognition,
    EnclosedAlphanumerics,
    BoxDrawing,
    BlockElements,
    GeometricShapes,
    MiscellaneousSymbols,
    Dingbats,
    MiscellaneousMathematicalSymbolsA,
    SupplementalArrowsA,
    BraillePatterns,
    SupplementalArrowsB,
    MiscellaneousMathematicalSymbolsB,
    SupplementalMathematicalOperators,
    MiscellaneousSymbolsandArrows,
    Glagolitic,
    LatinExtendedC,
    Coptic,
    GeorgianSupplement,
    Tifinagh,
    EthiopicExtended,
    CyrillicExtendedA,
    SupplementalPunctuation,
    CJKRadicalsSupplement,
    KangxiRadicals,
    IdeographicDescriptionCharacters,
    CJKSymbolsandPunctuation,
    Hiragana,
    Katakana,
    Bopomofo,
    HangulCompatibilityJamo,
    Kanbun,
    BopomofoExtended,
    CJKStrokes,
    KatakanaPhoneticExtensions,
    EnclosedCJKLettersandMonths,
    CJKCompatibility,
    CJKUnifiedIdeographsExtensionA,
    YijingHexagramSymbols,
    CJKUnifiedIdeographs,
    YiSyllables,
    YiRadicals,
    Lisu,
    Vai,
    CyrillicExtendedB,
    Bamum,
    ModifierToneLetters,
    LatinExtendedD,
    SylotiNagri,
    CommonIndicNumberForms,
    Phagspa,
    Saurashtra,
    DevanagariExtended,
    KayahLi,
    Rejang,
    HangulJamoExtendedA,
    Javanese,
    MyanmarExtendedB,
    Cham,
    MyanmarExtendedA,
    TaiViet,
    MeeteiMayekExtensions,
    EthiopicExtendedA,
    LatinExtendedE,
    CherokeeSupplement,
    MeeteiMayek,
    HangulSyllables,
    HangulJamoExtendedB,
    HighSurrogates,
    HighPrivateUseSurrogates,
    LowSurrogates,
    PrivateUseArea,
    CJKCompatibilityIdeographs,
    AlphabeticPresentationForms,
    ArabicPresentationFormsA,
    VariationSelectors,
    VerticalForms,
    CombiningHalfMarks,
    CJKCompatibilityForms,
    SmallFormVariants,
    ArabicPresentationFormsB,
    HalfwidthandFullwidthForms,
    Specials,
    LinearBSyllabary,
    LinearBIdeograms,
    AegeanNumbers,
    AncientGreekNumbers,
    AncientSymbols,
    PhaistosDisc,
    Lycian,
    Carian,
    CopticEpactNumbers,
    OldItalic,
    Gothic,
    OldPermic,
    Ugaritic,
    OldPersian,
    Deseret,
    Shavian,
    Osmanya,
    Osage,
    Elbasan,
    CaucasianAlbanian,
    LinearA,
    CypriotSyllabary,
    ImperialAramaic,
    Palmyrene,
    Nabataean,
    Hatran,
    Phoenician,
    Lydian,
    MeroiticHieroglyphs,
    MeroiticCursive,
    Kharoshthi,
    OldSouthArabian,
    OldNorthArabian,
    Manichaean,
    Avestan,
    InscriptionalParthian,
    InscriptionalPahlavi,
    PsalterPahlavi,
    OldTurkic,
    OldHungarian,
    RumiNumeralSymbols,
    Brahmi,
    Kaithi,
    SoraSompeng,
    Chakma,
    Mahajani,
    Sharada,
    SinhalaArchaicNumbers,
    Khojki,
    Multani,
    Khudawadi,
    Grantha,
    Newa,
    Tirhuta,
    Siddham,
    Modi,
    MongolianSupplement,
    Takri,
    Ahom,
    WarangCiti,
    ZanabazarSquare,
    Soyombo,
    PauCinHau,
    Bhaiksuki,
    Marchen,
    MasaramGondi,
    Cuneiform,
    CuneiformNumbersandPunctuation,
    EarlyDynasticCuneiform,
    EgyptianHieroglyphs,
    AnatolianHieroglyphs,
    BamumSupplement,
    Mro,
    BassaVah,
    PahawhHmong,
    Miao,
    IdeographicSymbolsandPunctuation,
    Tangut,
    TangutComponents,
    KanaSupplement,
    KanaExtendedA,
    Nushu,
    Duployan,
    ShorthandFormatControls,
    ByzantineMusicalSymbols,
    MusicalSymbols,
    AncientGreekMusicalNotation,
    TaiXuanJingSymbols,
    CountingRodNumerals,
    MathematicalAlphanumericSymbols,
    SuttonSignWriting,
    GlagoliticSupplement,
    MendeKikakui,
    Adlam,
    ArabicMathematicalAlphabeticSymbols,
    MahjongTiles,
    DominoTiles,
    PlayingCards,
    EnclosedAlphanumericSupplement,
    EnclosedIdeographicSupplement,
    MiscellaneousSymbolsandPictographs,
    Emoticons,
    OrnamentalDingbats,
    TransportandMapSymbols,
    AlchemicalSymbols,
    GeometricShapesExtended,
    SupplementalArrowsC,
    SupplementalSymbolsandPictographs,
    CJKUnifiedIdeographsExtensionB,
    CJKUnifiedIdeographsExtensionC,
    CJKUnifiedIdeographsExtensionD,
    CJKUnifiedIdeographsExtensionE,
    CJKUnifiedIdeographsExtensionF,
    CJKCompatibilityIdeographsSupplement,
    Tags,
    VariationSelectorsSupplement,
    SupplementaryPrivateUseAreaA,
    SupplementaryPrivateUseAreaB,
}
impl Block {
    pub fn first_codepoint(self) -> u32 {
        use self::Block::*;
        match self {
            BasicLatin => 0,
            Latin1Supplement => 128,
            LatinExtendedA => 256,
            LatinExtendedB => 384,
            IPAExtensions => 592,
            SpacingModifierLetters => 688,
            CombiningDiacriticalMarks => 768,
            GreekandCoptic => 880,
            Cyrillic => 1024,
            CyrillicSupplement => 1280,
            Armenian => 1328,
            Hebrew => 1424,
            Arabic => 1536,
            Syriac => 1792,
            ArabicSupplement => 1872,
            Thaana => 1920,
            NKo => 1984,
            Samaritan => 2048,
            Mandaic => 2112,
            SyriacSupplement => 2144,
            ArabicExtendedA => 2208,
            Devanagari => 2304,
            Bengali => 2432,
            Gurmukhi => 2560,
            Gujarati => 2688,
            Oriya => 2816,
            Tamil => 2944,
            Telugu => 3072,
            Kannada => 3200,
            Malayalam => 3328,
            Sinhala => 3456,
            Thai => 3584,
            Lao => 3712,
            Tibetan => 3840,
            Myanmar => 4096,
            Georgian => 4256,
            HangulJamo => 4352,
            Ethiopic => 4608,
            EthiopicSupplement => 4992,
            Cherokee => 5024,
            UnifiedCanadianAboriginalSyllabics => 5120,
            Ogham => 5760,
            Runic => 5792,
            Tagalog => 5888,
            Hanunoo => 5920,
            Buhid => 5952,
            Tagbanwa => 5984,
            Khmer => 6016,
            Mongolian => 6144,
            UnifiedCanadianAboriginalSyllabicsExtended => 6320,
            Limbu => 6400,
            TaiLe => 6480,
            NewTaiLue => 6528,
            KhmerSymbols => 6624,
            Buginese => 6656,
            TaiTham => 6688,
            CombiningDiacriticalMarksExtended => 6832,
            Balinese => 6912,
            Sundanese => 7040,
            Batak => 7104,
            Lepcha => 7168,
            OlChiki => 7248,
            CyrillicExtendedC => 7296,
            SundaneseSupplement => 7360,
            VedicExtensions => 7376,
            PhoneticExtensions => 7424,
            PhoneticExtensionsSupplement => 7552,
            CombiningDiacriticalMarksSupplement => 7616,
            LatinExtendedAdditional => 7680,
            GreekExtended => 7936,
            GeneralPunctuation => 8192,
            SuperscriptsandSubscripts => 8304,
            CurrencySymbols => 8352,
            CombiningDiacriticalMarksforSymbols => 8400,
            LetterlikeSymbols => 8448,
            NumberForms => 8528,
            Arrows => 8592,
            MathematicalOperators => 8704,
            MiscellaneousTechnical => 8960,
            ControlPictures => 9216,
            OpticalCharacterRecognition => 9280,
            EnclosedAlphanumerics => 9312,
            BoxDrawing => 9472,
            BlockElements => 9600,
            GeometricShapes => 9632,
            MiscellaneousSymbols => 9728,
            Dingbats => 9984,
            MiscellaneousMathematicalSymbolsA => 10176,
            SupplementalArrowsA => 10224,
            BraillePatterns => 10240,
            SupplementalArrowsB => 10496,
            MiscellaneousMathematicalSymbolsB => 10624,
            SupplementalMathematicalOperators => 10752,
            MiscellaneousSymbolsandArrows => 11008,
            Glagolitic => 11264,
            LatinExtendedC => 11360,
            Coptic => 11392,
            GeorgianSupplement => 11520,
            Tifinagh => 11568,
            EthiopicExtended => 11648,
            CyrillicExtendedA => 11744,
            SupplementalPunctuation => 11776,
            CJKRadicalsSupplement => 11904,
            KangxiRadicals => 12032,
            IdeographicDescriptionCharacters => 12272,
            CJKSymbolsandPunctuation => 12288,
            Hiragana => 12352,
            Katakana => 12448,
            Bopomofo => 12544,
            HangulCompatibilityJamo => 12592,
            Kanbun => 12688,
            BopomofoExtended => 12704,
            CJKStrokes => 12736,
            KatakanaPhoneticExtensions => 12784,
            EnclosedCJKLettersandMonths => 12800,
            CJKCompatibility => 13056,
            CJKUnifiedIdeographsExtensionA => 13312,
            YijingHexagramSymbols => 19904,
            CJKUnifiedIdeographs => 19968,
            YiSyllables => 40960,
            YiRadicals => 42128,
            Lisu => 42192,
            Vai => 42240,
            CyrillicExtendedB => 42560,
            Bamum => 42656,
            ModifierToneLetters => 42752,
            LatinExtendedD => 42784,
            SylotiNagri => 43008,
            CommonIndicNumberForms => 43056,
            Phagspa => 43072,
            Saurashtra => 43136,
            DevanagariExtended => 43232,
            KayahLi => 43264,
            Rejang => 43312,
            HangulJamoExtendedA => 43360,
            Javanese => 43392,
            MyanmarExtendedB => 43488,
            Cham => 43520,
            MyanmarExtendedA => 43616,
            TaiViet => 43648,
            MeeteiMayekExtensions => 43744,
            EthiopicExtendedA => 43776,
            LatinExtendedE => 43824,
            CherokeeSupplement => 43888,
            MeeteiMayek => 43968,
            HangulSyllables => 44032,
            HangulJamoExtendedB => 55216,
            HighSurrogates => 55296,
            HighPrivateUseSurrogates => 56192,
            LowSurrogates => 56320,
            PrivateUseArea => 57344,
            CJKCompatibilityIdeographs => 63744,
            AlphabeticPresentationForms => 64256,
            ArabicPresentationFormsA => 64336,
            VariationSelectors => 65024,
            VerticalForms => 65040,
            CombiningHalfMarks => 65056,
            CJKCompatibilityForms => 65072,
            SmallFormVariants => 65104,
            ArabicPresentationFormsB => 65136,
            HalfwidthandFullwidthForms => 65280,
            Specials => 65520,
            LinearBSyllabary => 65536,
            LinearBIdeograms => 65664,
            AegeanNumbers => 65792,
            AncientGreekNumbers => 65856,
            AncientSymbols => 65936,
            PhaistosDisc => 66000,
            Lycian => 66176,
            Carian => 66208,
            CopticEpactNumbers => 66272,
            OldItalic => 66304,
            Gothic => 66352,
            OldPermic => 66384,
            Ugaritic => 66432,
            OldPersian => 66464,
            Deseret => 66560,
            Shavian => 66640,
            Osmanya => 66688,
            Osage => 66736,
            Elbasan => 66816,
            CaucasianAlbanian => 66864,
            LinearA => 67072,
            CypriotSyllabary => 67584,
            ImperialAramaic => 67648,
            Palmyrene => 67680,
            Nabataean => 67712,
            Hatran => 67808,
            Phoenician => 67840,
            Lydian => 67872,
            MeroiticHieroglyphs => 67968,
            MeroiticCursive => 68000,
            Kharoshthi => 68096,
            OldSouthArabian => 68192,
            OldNorthArabian => 68224,
            Manichaean => 68288,
            Avestan => 68352,
            InscriptionalParthian => 68416,
            InscriptionalPahlavi => 68448,
            PsalterPahlavi => 68480,
            OldTurkic => 68608,
            OldHungarian => 68736,
            RumiNumeralSymbols => 69216,
            Brahmi => 69632,
            Kaithi => 69760,
            SoraSompeng => 69840,
            Chakma => 69888,
            Mahajani => 69968,
            Sharada => 70016,
            SinhalaArchaicNumbers => 70112,
            Khojki => 70144,
            Multani => 70272,
            Khudawadi => 70320,
            Grantha => 70400,
            Newa => 70656,
            Tirhuta => 70784,
            Siddham => 71040,
            Modi => 71168,
            MongolianSupplement => 71264,
            Takri => 71296,
            Ahom => 71424,
            WarangCiti => 71840,
            ZanabazarSquare => 72192,
            Soyombo => 72272,
            PauCinHau => 72384,
            Bhaiksuki => 72704,
            Marchen => 72816,
            MasaramGondi => 72960,
            Cuneiform => 73728,
            CuneiformNumbersandPunctuation => 74752,
            EarlyDynasticCuneiform => 74880,
            EgyptianHieroglyphs => 77824,
            AnatolianHieroglyphs => 82944,
            BamumSupplement => 92160,
            Mro => 92736,
            BassaVah => 92880,
            PahawhHmong => 92928,
            Miao => 93952,
            IdeographicSymbolsandPunctuation => 94176,
            Tangut => 94208,
            TangutComponents => 100352,
            KanaSupplement => 110592,
            KanaExtendedA => 110848,
            Nushu => 110960,
            Duployan => 113664,
            ShorthandFormatControls => 113824,
            ByzantineMusicalSymbols => 118784,
            MusicalSymbols => 119040,
            AncientGreekMusicalNotation => 119296,
            TaiXuanJingSymbols => 119552,
            CountingRodNumerals => 119648,
            MathematicalAlphanumericSymbols => 119808,
            SuttonSignWriting => 120832,
            GlagoliticSupplement => 122880,
            MendeKikakui => 124928,
            Adlam => 125184,
            ArabicMathematicalAlphabeticSymbols => 126464,
            MahjongTiles => 126976,
            DominoTiles => 127024,
            PlayingCards => 127136,
            EnclosedAlphanumericSupplement => 127232,
            EnclosedIdeographicSupplement => 127488,
            MiscellaneousSymbolsandPictographs => 127744,
            Emoticons => 128512,
            OrnamentalDingbats => 128592,
            TransportandMapSymbols => 128640,
            AlchemicalSymbols => 128768,
            GeometricShapesExtended => 128896,
            SupplementalArrowsC => 129024,
            SupplementalSymbolsandPictographs => 129280,
            CJKUnifiedIdeographsExtensionB => 131072,
            CJKUnifiedIdeographsExtensionC => 173824,
            CJKUnifiedIdeographsExtensionD => 177984,
            CJKUnifiedIdeographsExtensionE => 178208,
            CJKUnifiedIdeographsExtensionF => 183984,
            CJKCompatibilityIdeographsSupplement => 194560,
            Tags => 917504,
            VariationSelectorsSupplement => 917760,
            SupplementaryPrivateUseAreaA => 983040,
            SupplementaryPrivateUseAreaB => 1048576,
        }
    }
    pub fn last_codepoint(self) -> u32 {
        use self::Block::*;
        match self {
            BasicLatin => 127,
            Latin1Supplement => 255,
            LatinExtendedA => 383,
            LatinExtendedB => 591,
            IPAExtensions => 687,
            SpacingModifierLetters => 767,
            CombiningDiacriticalMarks => 879,
            GreekandCoptic => 1023,
            Cyrillic => 1279,
            CyrillicSupplement => 1327,
            Armenian => 1423,
            Hebrew => 1535,
            Arabic => 1791,
            Syriac => 1871,
            ArabicSupplement => 1919,
            Thaana => 1983,
            NKo => 2047,
            Samaritan => 2111,
            Mandaic => 2143,
            SyriacSupplement => 2159,
            ArabicExtendedA => 2303,
            Devanagari => 2431,
            Bengali => 2559,
            Gurmukhi => 2687,
            Gujarati => 2815,
            Oriya => 2943,
            Tamil => 3071,
            Telugu => 3199,
            Kannada => 3327,
            Malayalam => 3455,
            Sinhala => 3583,
            Thai => 3711,
            Lao => 3839,
            Tibetan => 4095,
            Myanmar => 4255,
            Georgian => 4351,
            HangulJamo => 4607,
            Ethiopic => 4991,
            EthiopicSupplement => 5023,
            Cherokee => 5119,
            UnifiedCanadianAboriginalSyllabics => 5759,
            Ogham => 5791,
            Runic => 5887,
            Tagalog => 5919,
            Hanunoo => 5951,
            Buhid => 5983,
            Tagbanwa => 6015,
            Khmer => 6143,
            Mongolian => 6319,
            UnifiedCanadianAboriginalSyllabicsExtended => 6399,
            Limbu => 6479,
            TaiLe => 6527,
            NewTaiLue => 6623,
            KhmerSymbols => 6655,
            Buginese => 6687,
            TaiTham => 6831,
            CombiningDiacriticalMarksExtended => 6911,
            Balinese => 7039,
            Sundanese => 7103,
            Batak => 7167,
            Lepcha => 7247,
            OlChiki => 7295,
            CyrillicExtendedC => 7311,
            SundaneseSupplement => 7375,
            VedicExtensions => 7423,
            PhoneticExtensions => 7551,
            PhoneticExtensionsSupplement => 7615,
            CombiningDiacriticalMarksSupplement => 7679,
            LatinExtendedAdditional => 7935,
            GreekExtended => 8191,
            GeneralPunctuation => 8303,
            SuperscriptsandSubscripts => 8351,
            CurrencySymbols => 8399,
            CombiningDiacriticalMarksforSymbols => 8447,
            LetterlikeSymbols => 8527,
            NumberForms => 8591,
            Arrows => 8703,
            MathematicalOperators => 8959,
            MiscellaneousTechnical => 9215,
            ControlPictures => 9279,
            OpticalCharacterRecognition => 9311,
            EnclosedAlphanumerics => 9471,
            BoxDrawing => 9599,
            BlockElements => 9631,
            GeometricShapes => 9727,
            MiscellaneousSymbols => 9983,
            Dingbats => 10175,
            MiscellaneousMathematicalSymbolsA => 10223,
            SupplementalArrowsA => 10239,
            BraillePatterns => 10495,
            SupplementalArrowsB => 10623,
            MiscellaneousMathematicalSymbolsB => 10751,
            SupplementalMathematicalOperators => 11007,
            MiscellaneousSymbolsandArrows => 11263,
            Glagolitic => 11359,
            LatinExtendedC => 11391,
            Coptic => 11519,
            GeorgianSupplement => 11567,
            Tifinagh => 11647,
            EthiopicExtended => 11743,
            CyrillicExtendedA => 11775,
            SupplementalPunctuation => 11903,
            CJKRadicalsSupplement => 12031,
            KangxiRadicals => 12255,
            IdeographicDescriptionCharacters => 12287,
            CJKSymbolsandPunctuation => 12351,
            Hiragana => 12447,
            Katakana => 12543,
            Bopomofo => 12591,
            HangulCompatibilityJamo => 12687,
            Kanbun => 12703,
            BopomofoExtended => 12735,
            CJKStrokes => 12783,
            KatakanaPhoneticExtensions => 12799,
            EnclosedCJKLettersandMonths => 13055,
            CJKCompatibility => 13311,
            CJKUnifiedIdeographsExtensionA => 19903,
            YijingHexagramSymbols => 19967,
            CJKUnifiedIdeographs => 40959,
            YiSyllables => 42127,
            YiRadicals => 42191,
            Lisu => 42239,
            Vai => 42559,
            CyrillicExtendedB => 42655,
            Bamum => 42751,
            ModifierToneLetters => 42783,
            LatinExtendedD => 43007,
            SylotiNagri => 43055,
            CommonIndicNumberForms => 43071,
            Phagspa => 43135,
            Saurashtra => 43231,
            DevanagariExtended => 43263,
            KayahLi => 43311,
            Rejang => 43359,
            HangulJamoExtendedA => 43391,
            Javanese => 43487,
            MyanmarExtendedB => 43519,
            Cham => 43615,
            MyanmarExtendedA => 43647,
            TaiViet => 43743,
            MeeteiMayekExtensions => 43775,
            EthiopicExtendedA => 43823,
            LatinExtendedE => 43887,
            CherokeeSupplement => 43967,
            MeeteiMayek => 44031,
            HangulSyllables => 55215,
            HangulJamoExtendedB => 55295,
            HighSurrogates => 56191,
            HighPrivateUseSurrogates => 56319,
            LowSurrogates => 57343,
            PrivateUseArea => 63743,
            CJKCompatibilityIdeographs => 64255,
            AlphabeticPresentationForms => 64335,
            ArabicPresentationFormsA => 65023,
            VariationSelectors => 65039,
            VerticalForms => 65055,
            CombiningHalfMarks => 65071,
            CJKCompatibilityForms => 65103,
            SmallFormVariants => 65135,
            ArabicPresentationFormsB => 65279,
            HalfwidthandFullwidthForms => 65519,
            Specials => 65535,
            LinearBSyllabary => 65663,
            LinearBIdeograms => 65791,
            AegeanNumbers => 65855,
            AncientGreekNumbers => 65935,
            AncientSymbols => 65999,
            PhaistosDisc => 66047,
            Lycian => 66207,
            Carian => 66271,
            CopticEpactNumbers => 66303,
            OldItalic => 66351,
            Gothic => 66383,
            OldPermic => 66431,
            Ugaritic => 66463,
            OldPersian => 66527,
            Deseret => 66639,
            Shavian => 66687,
            Osmanya => 66735,
            Osage => 66815,
            Elbasan => 66863,
            CaucasianAlbanian => 66927,
            LinearA => 67455,
            CypriotSyllabary => 67647,
            ImperialAramaic => 67679,
            Palmyrene => 67711,
            Nabataean => 67759,
            Hatran => 67839,
            Phoenician => 67871,
            Lydian => 67903,
            MeroiticHieroglyphs => 67999,
            MeroiticCursive => 68095,
            Kharoshthi => 68191,
            OldSouthArabian => 68223,
            OldNorthArabian => 68255,
            Manichaean => 68351,
            Avestan => 68415,
            InscriptionalParthian => 68447,
            InscriptionalPahlavi => 68479,
            PsalterPahlavi => 68527,
            OldTurkic => 68687,
            OldHungarian => 68863,
            RumiNumeralSymbols => 69247,
            Brahmi => 69759,
            Kaithi => 69839,
            SoraSompeng => 69887,
            Chakma => 69967,
            Mahajani => 70015,
            Sharada => 70111,
            SinhalaArchaicNumbers => 70143,
            Khojki => 70223,
            Multani => 70319,
            Khudawadi => 70399,
            Grantha => 70527,
            Newa => 70783,
            Tirhuta => 70879,
            Siddham => 71167,
            Modi => 71263,
            MongolianSupplement => 71295,
            Takri => 71375,
            Ahom => 71487,
            WarangCiti => 71935,
            ZanabazarSquare => 72271,
            Soyombo => 72367,
            PauCinHau => 72447,
            Bhaiksuki => 72815,
            Marchen => 72895,
            MasaramGondi => 73055,
            Cuneiform => 74751,
            CuneiformNumbersandPunctuation => 74879,
            EarlyDynasticCuneiform => 75087,
            EgyptianHieroglyphs => 78895,
            AnatolianHieroglyphs => 83583,
            BamumSupplement => 92735,
            Mro => 92783,
            BassaVah => 92927,
            PahawhHmong => 93071,
            Miao => 94111,
            IdeographicSymbolsandPunctuation => 94207,
            Tangut => 100351,
            TangutComponents => 101119,
            KanaSupplement => 110847,
            KanaExtendedA => 110895,
            Nushu => 111359,
            Duployan => 113823,
            ShorthandFormatControls => 113839,
            ByzantineMusicalSymbols => 119039,
            MusicalSymbols => 119295,
            AncientGreekMusicalNotation => 119375,
            TaiXuanJingSymbols => 119647,
            CountingRodNumerals => 119679,
            MathematicalAlphanumericSymbols => 120831,
            SuttonSignWriting => 121519,
            GlagoliticSupplement => 122927,
            MendeKikakui => 125151,
            Adlam => 125279,
            ArabicMathematicalAlphabeticSymbols => 126719,
            MahjongTiles => 127023,
            DominoTiles => 127135,
            PlayingCards => 127231,
            EnclosedAlphanumericSupplement => 127487,
            EnclosedIdeographicSupplement => 127743,
            MiscellaneousSymbolsandPictographs => 128511,
            Emoticons => 128591,
            OrnamentalDingbats => 128639,
            TransportandMapSymbols => 128767,
            AlchemicalSymbols => 128895,
            GeometricShapesExtended => 129023,
            SupplementalArrowsC => 129279,
            SupplementalSymbolsandPictographs => 129535,
            CJKUnifiedIdeographsExtensionB => 173791,
            CJKUnifiedIdeographsExtensionC => 177983,
            CJKUnifiedIdeographsExtensionD => 178207,
            CJKUnifiedIdeographsExtensionE => 183983,
            CJKUnifiedIdeographsExtensionF => 191471,
            CJKCompatibilityIdeographsSupplement => 195103,
            Tags => 917631,
            VariationSelectorsSupplement => 917999,
            SupplementaryPrivateUseAreaA => 1048575,
            SupplementaryPrivateUseAreaB => 1114111,
        }
    }
    pub fn contains_char(self, c: char) -> bool {
        let codepoint = c as u32;
        codepoint >= self.first_codepoint() && codepoint <= self.last_codepoint()
    }
    pub fn chart(self) -> String {
        format!(
            "https://www.unicode.org/charts/PDF/U{:04X}.pdf",
            self.first_codepoint()
        )
    }
    pub fn name(self) -> &'static str {
        use self::Block::*;
        match self {
            BasicLatin => "Basic Latin",
            Latin1Supplement => "Latin-1 Supplement",
            LatinExtendedA => "Latin Extended-A",
            LatinExtendedB => "Latin Extended-B",
            IPAExtensions => "IPA Extensions",
            SpacingModifierLetters => "Spacing Modifier Letters",
            CombiningDiacriticalMarks => "Combining Diacritical Marks",
            GreekandCoptic => "Greek and Coptic",
            Cyrillic => "Cyrillic",
            CyrillicSupplement => "Cyrillic Supplement",
            Armenian => "Armenian",
            Hebrew => "Hebrew",
            Arabic => "Arabic",
            Syriac => "Syriac",
            ArabicSupplement => "Arabic Supplement",
            Thaana => "Thaana",
            NKo => "NKo",
            Samaritan => "Samaritan",
            Mandaic => "Mandaic",
            SyriacSupplement => "Syriac Supplement",
            ArabicExtendedA => "Arabic Extended-A",
            Devanagari => "Devanagari",
            Bengali => "Bengali",
            Gurmukhi => "Gurmukhi",
            Gujarati => "Gujarati",
            Oriya => "Oriya",
            Tamil => "Tamil",
            Telugu => "Telugu",
            Kannada => "Kannada",
            Malayalam => "Malayalam",
            Sinhala => "Sinhala",
            Thai => "Thai",
            Lao => "Lao",
            Tibetan => "Tibetan",
            Myanmar => "Myanmar",
            Georgian => "Georgian",
            HangulJamo => "Hangul Jamo",
            Ethiopic => "Ethiopic",
            EthiopicSupplement => "Ethiopic Supplement",
            Cherokee => "Cherokee",
            UnifiedCanadianAboriginalSyllabics => "Unified Canadian Aboriginal Syllabics",
            Ogham => "Ogham",
            Runic => "Runic",
            Tagalog => "Tagalog",
            Hanunoo => "Hanunoo",
            Buhid => "Buhid",
            Tagbanwa => "Tagbanwa",
            Khmer => "Khmer",
            Mongolian => "Mongolian",
            UnifiedCanadianAboriginalSyllabicsExtended => {
                "Unified Canadian Aboriginal Syllabics Extended"
            }
            Limbu => "Limbu",
            TaiLe => "Tai Le",
            NewTaiLue => "New Tai Lue",
            KhmerSymbols => "Khmer Symbols",
            Buginese => "Buginese",
            TaiTham => "Tai Tham",
            CombiningDiacriticalMarksExtended => "Combining Diacritical Marks Extended",
            Balinese => "Balinese",
            Sundanese => "Sundanese",
            Batak => "Batak",
            Lepcha => "Lepcha",
            OlChiki => "Ol Chiki",
            CyrillicExtendedC => "Cyrillic Extended-C",
            SundaneseSupplement => "Sundanese Supplement",
            VedicExtensions => "Vedic Extensions",
            PhoneticExtensions => "Phonetic Extensions",
            PhoneticExtensionsSupplement => "Phonetic Extensions Supplement",
            CombiningDiacriticalMarksSupplement => "Combining Diacritical Marks Supplement",
            LatinExtendedAdditional => "Latin Extended Additional",
            GreekExtended => "Greek Extended",
            GeneralPunctuation => "General Punctuation",
            SuperscriptsandSubscripts => "Superscripts and Subscripts",
            CurrencySymbols => "Currency Symbols",
            CombiningDiacriticalMarksforSymbols => "Combining Diacritical Marks for Symbols",
            LetterlikeSymbols => "Letterlike Symbols",
            NumberForms => "Number Forms",
            Arrows => "Arrows",
            MathematicalOperators => "Mathematical Operators",
            MiscellaneousTechnical => "Miscellaneous Technical",
            ControlPictures => "Control Pictures",
            OpticalCharacterRecognition => "Optical Character Recognition",
            EnclosedAlphanumerics => "Enclosed Alphanumerics",
            BoxDrawing => "Box Drawing",
            BlockElements => "Block Elements",
            GeometricShapes => "Geometric Shapes",
            MiscellaneousSymbols => "Miscellaneous Symbols",
            Dingbats => "Dingbats",
            MiscellaneousMathematicalSymbolsA => "Miscellaneous Mathematical Symbols-A",
            SupplementalArrowsA => "Supplemental Arrows-A",
            BraillePatterns => "Braille Patterns",
            SupplementalArrowsB => "Supplemental Arrows-B",
            MiscellaneousMathematicalSymbolsB => "Miscellaneous Mathematical Symbols-B",
            SupplementalMathematicalOperators => "Supplemental Mathematical Operators",
            MiscellaneousSymbolsandArrows => "Miscellaneous Symbols and Arrows",
            Glagolitic => "Glagolitic",
            LatinExtendedC => "Latin Extended-C",
            Coptic => "Coptic",
            GeorgianSupplement => "Georgian Supplement",
            Tifinagh => "Tifinagh",
            EthiopicExtended => "Ethiopic Extended",
            CyrillicExtendedA => "Cyrillic Extended-A",
            SupplementalPunctuation => "Supplemental Punctuation",
            CJKRadicalsSupplement => "CJK Radicals Supplement",
            KangxiRadicals => "Kangxi Radicals",
            IdeographicDescriptionCharacters => "Ideographic Description Characters",
            CJKSymbolsandPunctuation => "CJK Symbols and Punctuation",
            Hiragana => "Hiragana",
            Katakana => "Katakana",
            Bopomofo => "Bopomofo",
            HangulCompatibilityJamo => "Hangul Compatibility Jamo",
            Kanbun => "Kanbun",
            BopomofoExtended => "Bopomofo Extended",
            CJKStrokes => "CJK Strokes",
            KatakanaPhoneticExtensions => "Katakana Phonetic Extensions",
            EnclosedCJKLettersandMonths => "Enclosed CJK Letters and Months",
            CJKCompatibility => "CJK Compatibility",
            CJKUnifiedIdeographsExtensionA => "CJK Unified Ideographs Extension A",
            YijingHexagramSymbols => "Yijing Hexagram Symbols",
            CJKUnifiedIdeographs => "CJK Unified Ideographs",
            YiSyllables => "Yi Syllables",
            YiRadicals => "Yi Radicals",
            Lisu => "Lisu",
            Vai => "Vai",
            CyrillicExtendedB => "Cyrillic Extended-B",
            Bamum => "Bamum",
            ModifierToneLetters => "Modifier Tone Letters",
            LatinExtendedD => "Latin Extended-D",
            SylotiNagri => "Syloti Nagri",
            CommonIndicNumberForms => "Common Indic Number Forms",
            Phagspa => "Phags-pa",
            Saurashtra => "Saurashtra",
            DevanagariExtended => "Devanagari Extended",
            KayahLi => "Kayah Li",
            Rejang => "Rejang",
            HangulJamoExtendedA => "Hangul Jamo Extended-A",
            Javanese => "Javanese",
            MyanmarExtendedB => "Myanmar Extended-B",
            Cham => "Cham",
            MyanmarExtendedA => "Myanmar Extended-A",
            TaiViet => "Tai Viet",
            MeeteiMayekExtensions => "Meetei Mayek Extensions",
            EthiopicExtendedA => "Ethiopic Extended-A",
            LatinExtendedE => "Latin Extended-E",
            CherokeeSupplement => "Cherokee Supplement",
            MeeteiMayek => "Meetei Mayek",
            HangulSyllables => "Hangul Syllables",
            HangulJamoExtendedB => "Hangul Jamo Extended-B",
            HighSurrogates => "High Surrogates",
            HighPrivateUseSurrogates => "High Private Use Surrogates",
            LowSurrogates => "Low Surrogates",
            PrivateUseArea => "Private Use Area",
            CJKCompatibilityIdeographs => "CJK Compatibility Ideographs",
            AlphabeticPresentationForms => "Alphabetic Presentation Forms",
            ArabicPresentationFormsA => "Arabic Presentation Forms-A",
            VariationSelectors => "Variation Selectors",
            VerticalForms => "Vertical Forms",
            CombiningHalfMarks => "Combining Half Marks",
            CJKCompatibilityForms => "CJK Compatibility Forms",
            SmallFormVariants => "Small Form Variants",
            ArabicPresentationFormsB => "Arabic Presentation Forms-B",
            HalfwidthandFullwidthForms => "Halfwidth and Fullwidth Forms",
            Specials => "Specials",
            LinearBSyllabary => "Linear B Syllabary",
            LinearBIdeograms => "Linear B Ideograms",
            AegeanNumbers => "Aegean Numbers",
            AncientGreekNumbers => "Ancient Greek Numbers",
            AncientSymbols => "Ancient Symbols",
            PhaistosDisc => "Phaistos Disc",
            Lycian => "Lycian",
            Carian => "Carian",
            CopticEpactNumbers => "Coptic Epact Numbers",
            OldItalic => "Old Italic",
            Gothic => "Gothic",
            OldPermic => "Old Permic",
            Ugaritic => "Ugaritic",
            OldPersian => "Old Persian",
            Deseret => "Deseret",
            Shavian => "Shavian",
            Osmanya => "Osmanya",
            Osage => "Osage",
            Elbasan => "Elbasan",
            CaucasianAlbanian => "Caucasian Albanian",
            LinearA => "Linear A",
            CypriotSyllabary => "Cypriot Syllabary",
            ImperialAramaic => "Imperial Aramaic",
            Palmyrene => "Palmyrene",
            Nabataean => "Nabataean",
            Hatran => "Hatran",
            Phoenician => "Phoenician",
            Lydian => "Lydian",
            MeroiticHieroglyphs => "Meroitic Hieroglyphs",
            MeroiticCursive => "Meroitic Cursive",
            Kharoshthi => "Kharoshthi",
            OldSouthArabian => "Old South Arabian",
            OldNorthArabian => "Old North Arabian",
            Manichaean => "Manichaean",
            Avestan => "Avestan",
            InscriptionalParthian => "Inscriptional Parthian",
            InscriptionalPahlavi => "Inscriptional Pahlavi",
            PsalterPahlavi => "Psalter Pahlavi",
            OldTurkic => "Old Turkic",
            OldHungarian => "Old Hungarian",
            RumiNumeralSymbols => "Rumi Numeral Symbols",
            Brahmi => "Brahmi",
            Kaithi => "Kaithi",
            SoraSompeng => "Sora Sompeng",
            Chakma => "Chakma",
            Mahajani => "Mahajani",
            Sharada => "Sharada",
            SinhalaArchaicNumbers => "Sinhala Archaic Numbers",
            Khojki => "Khojki",
            Multani => "Multani",
            Khudawadi => "Khudawadi",
            Grantha => "Grantha",
            Newa => "Newa",
            Tirhuta => "Tirhuta",
            Siddham => "Siddham",
            Modi => "Modi",
            MongolianSupplement => "Mongolian Supplement",
            Takri => "Takri",
            Ahom => "Ahom",
            WarangCiti => "Warang Citi",
            ZanabazarSquare => "Zanabazar Square",
            Soyombo => "Soyombo",
            PauCinHau => "Pau Cin Hau",
            Bhaiksuki => "Bhaiksuki",
            Marchen => "Marchen",
            MasaramGondi => "Masaram Gondi",
            Cuneiform => "Cuneiform",
            CuneiformNumbersandPunctuation => "Cuneiform Numbers and Punctuation",
            EarlyDynasticCuneiform => "Early Dynastic Cuneiform",
            EgyptianHieroglyphs => "Egyptian Hieroglyphs",
            AnatolianHieroglyphs => "Anatolian Hieroglyphs",
            BamumSupplement => "Bamum Supplement",
            Mro => "Mro",
            BassaVah => "Bassa Vah",
            PahawhHmong => "Pahawh Hmong",
            Miao => "Miao",
            IdeographicSymbolsandPunctuation => "Ideographic Symbols and Punctuation",
            Tangut => "Tangut",
            TangutComponents => "Tangut Components",
            KanaSupplement => "Kana Supplement",
            KanaExtendedA => "Kana Extended-A",
            Nushu => "Nushu",
            Duployan => "Duployan",
            ShorthandFormatControls => "Shorthand Format Controls",
            ByzantineMusicalSymbols => "Byzantine Musical Symbols",
            MusicalSymbols => "Musical Symbols",
            AncientGreekMusicalNotation => "Ancient Greek Musical Notation",
            TaiXuanJingSymbols => "Tai Xuan Jing Symbols",
            CountingRodNumerals => "Counting Rod Numerals",
            MathematicalAlphanumericSymbols => "Mathematical Alphanumeric Symbols",
            SuttonSignWriting => "Sutton SignWriting",
            GlagoliticSupplement => "Glagolitic Supplement",
            MendeKikakui => "Mende Kikakui",
            Adlam => "Adlam",
            ArabicMathematicalAlphabeticSymbols => "Arabic Mathematical Alphabetic Symbols",
            MahjongTiles => "Mahjong Tiles",
            DominoTiles => "Domino Tiles",
            PlayingCards => "Playing Cards",
            EnclosedAlphanumericSupplement => "Enclosed Alphanumeric Supplement",
            EnclosedIdeographicSupplement => "Enclosed Ideographic Supplement",
            MiscellaneousSymbolsandPictographs => "Miscellaneous Symbols and Pictographs",
            Emoticons => "Emoticons",
            OrnamentalDingbats => "Ornamental Dingbats",
            TransportandMapSymbols => "Transport and Map Symbols",
            AlchemicalSymbols => "Alchemical Symbols",
            GeometricShapesExtended => "Geometric Shapes Extended",
            SupplementalArrowsC => "Supplemental Arrows-C",
            SupplementalSymbolsandPictographs => "Supplemental Symbols and Pictographs",
            CJKUnifiedIdeographsExtensionB => "CJK Unified Ideographs Extension B",
            CJKUnifiedIdeographsExtensionC => "CJK Unified Ideographs Extension C",
            CJKUnifiedIdeographsExtensionD => "CJK Unified Ideographs Extension D",
            CJKUnifiedIdeographsExtensionE => "CJK Unified Ideographs Extension E",
            CJKUnifiedIdeographsExtensionF => "CJK Unified Ideographs Extension F",
            CJKCompatibilityIdeographsSupplement => "CJK Compatibility Ideographs Supplement",
            Tags => "Tags",
            VariationSelectorsSupplement => "Variation Selectors Supplement",
            SupplementaryPrivateUseAreaA => "Supplementary Private Use Area-A",
            SupplementaryPrivateUseAreaB => "Supplementary Private Use Area-B",
        }
    }
    pub fn surrogates(self) -> bool {
        use self::Block::*;
        match self {
            HighSurrogates | HighPrivateUseSurrogates | LowSurrogates => true,
            _ => false,
        }
    }
    pub fn boring(self) -> bool {
        use self::Block::*;
        match self {
            Tags
            | VariationSelectorsSupplement
            | PrivateUseArea
            | SupplementaryPrivateUseAreaA
            | SupplementaryPrivateUseAreaB => true,
            _ => false,
        }
    }
    pub fn all() -> &'static [Block] {
        use self::Block::*;
        &[
            BasicLatin,
            Latin1Supplement,
            LatinExtendedA,
            LatinExtendedB,
            IPAExtensions,
            SpacingModifierLetters,
            CombiningDiacriticalMarks,
            GreekandCoptic,
            Cyrillic,
            CyrillicSupplement,
            Armenian,
            Hebrew,
            Arabic,
            Syriac,
            ArabicSupplement,
            Thaana,
            NKo,
            Samaritan,
            Mandaic,
            SyriacSupplement,
            ArabicExtendedA,
            Devanagari,
            Bengali,
            Gurmukhi,
            Gujarati,
            Oriya,
            Tamil,
            Telugu,
            Kannada,
            Malayalam,
            Sinhala,
            Thai,
            Lao,
            Tibetan,
            Myanmar,
            Georgian,
            HangulJamo,
            Ethiopic,
            EthiopicSupplement,
            Cherokee,
            UnifiedCanadianAboriginalSyllabics,
            Ogham,
            Runic,
            Tagalog,
            Hanunoo,
            Buhid,
            Tagbanwa,
            Khmer,
            Mongolian,
            UnifiedCanadianAboriginalSyllabicsExtended,
            Limbu,
            TaiLe,
            NewTaiLue,
            KhmerSymbols,
            Buginese,
            TaiTham,
            CombiningDiacriticalMarksExtended,
            Balinese,
            Sundanese,
            Batak,
            Lepcha,
            OlChiki,
            CyrillicExtendedC,
            SundaneseSupplement,
            VedicExtensions,
            PhoneticExtensions,
            PhoneticExtensionsSupplement,
            CombiningDiacriticalMarksSupplement,
            LatinExtendedAdditional,
            GreekExtended,
            GeneralPunctuation,
            SuperscriptsandSubscripts,
            CurrencySymbols,
            CombiningDiacriticalMarksforSymbols,
            LetterlikeSymbols,
            NumberForms,
            Arrows,
            MathematicalOperators,
            MiscellaneousTechnical,
            ControlPictures,
            OpticalCharacterRecognition,
            EnclosedAlphanumerics,
            BoxDrawing,
            BlockElements,
            GeometricShapes,
            MiscellaneousSymbols,
            Dingbats,
            MiscellaneousMathematicalSymbolsA,
            SupplementalArrowsA,
            BraillePatterns,
            SupplementalArrowsB,
            MiscellaneousMathematicalSymbolsB,
            SupplementalMathematicalOperators,
            MiscellaneousSymbolsandArrows,
            Glagolitic,
            LatinExtendedC,
            Coptic,
            GeorgianSupplement,
            Tifinagh,
            EthiopicExtended,
            CyrillicExtendedA,
            SupplementalPunctuation,
            CJKRadicalsSupplement,
            KangxiRadicals,
            IdeographicDescriptionCharacters,
            CJKSymbolsandPunctuation,
            Hiragana,
            Katakana,
            Bopomofo,
            HangulCompatibilityJamo,
            Kanbun,
            BopomofoExtended,
            CJKStrokes,
            KatakanaPhoneticExtensions,
            EnclosedCJKLettersandMonths,
            CJKCompatibility,
            CJKUnifiedIdeographsExtensionA,
            YijingHexagramSymbols,
            CJKUnifiedIdeographs,
            YiSyllables,
            YiRadicals,
            Lisu,
            Vai,
            CyrillicExtendedB,
            Bamum,
            ModifierToneLetters,
            LatinExtendedD,
            SylotiNagri,
            CommonIndicNumberForms,
            Phagspa,
            Saurashtra,
            DevanagariExtended,
            KayahLi,
            Rejang,
            HangulJamoExtendedA,
            Javanese,
            MyanmarExtendedB,
            Cham,
            MyanmarExtendedA,
            TaiViet,
            MeeteiMayekExtensions,
            EthiopicExtendedA,
            LatinExtendedE,
            CherokeeSupplement,
            MeeteiMayek,
            HangulSyllables,
            HangulJamoExtendedB,
            HighSurrogates,
            HighPrivateUseSurrogates,
            LowSurrogates,
            PrivateUseArea,
            CJKCompatibilityIdeographs,
            AlphabeticPresentationForms,
            ArabicPresentationFormsA,
            VariationSelectors,
            VerticalForms,
            CombiningHalfMarks,
            CJKCompatibilityForms,
            SmallFormVariants,
            ArabicPresentationFormsB,
            HalfwidthandFullwidthForms,
            Specials,
            LinearBSyllabary,
            LinearBIdeograms,
            AegeanNumbers,
            AncientGreekNumbers,
            AncientSymbols,
            PhaistosDisc,
            Lycian,
            Carian,
            CopticEpactNumbers,
            OldItalic,
            Gothic,
            OldPermic,
            Ugaritic,
            OldPersian,
            Deseret,
            Shavian,
            Osmanya,
            Osage,
            Elbasan,
            CaucasianAlbanian,
            LinearA,
            CypriotSyllabary,
            ImperialAramaic,
            Palmyrene,
            Nabataean,
            Hatran,
            Phoenician,
            Lydian,
            MeroiticHieroglyphs,
            MeroiticCursive,
            Kharoshthi,
            OldSouthArabian,
            OldNorthArabian,
            Manichaean,
            Avestan,
            InscriptionalParthian,
            InscriptionalPahlavi,
            PsalterPahlavi,
            OldTurkic,
            OldHungarian,
            RumiNumeralSymbols,
            Brahmi,
            Kaithi,
            SoraSompeng,
            Chakma,
            Mahajani,
            Sharada,
            SinhalaArchaicNumbers,
            Khojki,
            Multani,
            Khudawadi,
            Grantha,
            Newa,
            Tirhuta,
            Siddham,
            Modi,
            MongolianSupplement,
            Takri,
            Ahom,
            WarangCiti,
            ZanabazarSquare,
            Soyombo,
            PauCinHau,
            Bhaiksuki,
            Marchen,
            MasaramGondi,
            Cuneiform,
            CuneiformNumbersandPunctuation,
            EarlyDynasticCuneiform,
            EgyptianHieroglyphs,
            AnatolianHieroglyphs,
            BamumSupplement,
            Mro,
            BassaVah,
            PahawhHmong,
            Miao,
            IdeographicSymbolsandPunctuation,
            Tangut,
            TangutComponents,
            KanaSupplement,
            KanaExtendedA,
            Nushu,
            Duployan,
            ShorthandFormatControls,
            ByzantineMusicalSymbols,
            MusicalSymbols,
            AncientGreekMusicalNotation,
            TaiXuanJingSymbols,
            CountingRodNumerals,
            MathematicalAlphanumericSymbols,
            SuttonSignWriting,
            GlagoliticSupplement,
            MendeKikakui,
            Adlam,
            ArabicMathematicalAlphabeticSymbols,
            MahjongTiles,
            DominoTiles,
            PlayingCards,
            EnclosedAlphanumericSupplement,
            EnclosedIdeographicSupplement,
            MiscellaneousSymbolsandPictographs,
            Emoticons,
            OrnamentalDingbats,
            TransportandMapSymbols,
            AlchemicalSymbols,
            GeometricShapesExtended,
            SupplementalArrowsC,
            SupplementalSymbolsandPictographs,
            CJKUnifiedIdeographsExtensionB,
            CJKUnifiedIdeographsExtensionC,
            CJKUnifiedIdeographsExtensionD,
            CJKUnifiedIdeographsExtensionE,
            CJKUnifiedIdeographsExtensionF,
            CJKCompatibilityIdeographsSupplement,
            Tags,
            VariationSelectorsSupplement,
            SupplementaryPrivateUseAreaA,
            SupplementaryPrivateUseAreaB,
        ]
    }
}
